### ISSUE TITLE
Use mypyc when building wheels

### ISSUE THREAD

**Issue by lucaswiman** [erikrose/parsimonious#210]
See [Gyph's article](https://glyph.twistedmatrix.com/2022/04/you-should-compile-your-python-and-heres-why.html) and the [documentation](https://mypyc.readthedocs.io/en/latest/index.html). The basic idea is to annotate some basic types which can allow automatically compiling to more optimized C code that is equivalent to the original python. Basically Cython without a custom DSL, and that works on native types.

In particular, since we know that `match_core` and `expressions.py` are hotspots, a few annotations may significantly increase the speed. `expr_cache` is essentially a `Dict[int, Dict[int, Optional[Node]]]`, so the key lookups may be significantly faster when compiled to C. `match_core` and a few other methods could be factored out into their own modules to reduce the the surface area that mypyc would touch.

Some downsides are that it would make the build process more complicated, and possibly make error messages more opaque for end users.

## Tasks
* [x] Make basic setup and see if it improves performance at all on match_core.
* [ ] Try finding a few other hotspots (e.g. literal matching?) and profile at each stage.
* [ ] Update the CI to generate wheels as artifacts as described in the Glyph post.

**Comment by lucaswiman** [comment]
I did some benchmarking on this and wasn't able to get any noticeable speedup. Maybe if all of expressions.py were written to mypyc's satisfaction, but that seems to be tricky. This may be worth revisiting later once mypyc is more mature and maybe after more of parsimonious is annotated.
